pipeline{
    agent any
    parameters{
        CODE_REPO = "https://github.com/Daver-Creations/DevSecOps.git"
        CODE_DIR = "Mango"
        IMAGE_NAME = "mango"
        IMAGE_TAG = "v${IMAGE_NAME}"
    }
    stages{
        stage("clone project"){
            steps{
                script{
                    sh 'git clone ${CODE_REPO}'
                }
            }
        }

        stage("build docker image"){
            steps{
                script{
                    dir("${CODE_DIR}")
                    sh 'docker build -t ${IMAGE_NAME} .'
                }
            }
        }

        stage("push to ecr"){
            steps{
                script{
                    sh 'docker images'
                }
            }
        }
    }
}